[build]
  command = "npx convex deploy --cmd 'npm run build' --cmd-url-env-var-name VITE_CONVEX_URL --preview-run 'crm:ensureSeedData'"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
